[package]
name = "rtree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rstar = "0.12.0"
rand = "0.9.0-alpha.2"
rand_chacha = "0.9.0-alpha.2"
